import { notFound } from "next/navigation";
import Link from "next/link";
import { getAdminLogs } from "../../../../lib/database";
import { getSubscriptions, getSubscriptionPayments } from "../../../../lib/subscriptions";
import AdminPageHeader from "../../AdminPageHeader";
import { EXTRA_USER_PRICE, formatNumber, getRenewalAlert, statusClass } from "../../utils";

export default async function AdminClientProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const tenantId = decodeURIComponent(id);
  const [subscriptions, payments, logs] = await Promise.all([getSubscriptions(), getSubscriptionPayments(), getAdminLogs()]);
  const client = subscriptions.find((item) => item.tenantId === tenantId); if (!client) notFound();
  const clientPayments = payments.filter((item) => item.tenantId === tenantId).sort((a,b) => (b.createdAt || "").localeCompare(a.createdAt || ""));
  const clientLogs = logs.filter((item) => item.clientId === tenantId).reverse();
  const paid = clientPayments.filter((item) => item.status === "مكتمل").reduce((sum,item) => sum + item.amount, 0); const pending = clientPayments.filter((item) => item.status === "قيد الانتظار").reduce((sum,item) => sum + item.amount, 0);
  const extraUsers = Math.max(0, client.employeeCount - client.employeeLimit); const invoice = client.amount + extraUsers * EXTRA_USER_PRICE; const renewal = getRenewalAlert(client);
  return <><AdminPageHeader eyebrow={["ملف العميل", "Client profile"]} title={[client.companyName, client.companyName]} description={["ملف موحد للاشتراك والفوترة والاستخدام وسجل الحركة.", "A unified profile for subscription, billing, usage, and activity."]} />
    <section className="admin-client-profile-hero"><div className="admin-client-avatar">{client.companyName.slice(0,1)}</div><div><span className={`admin-pill ${statusClass(client.status)}`}>{client.status}</span><h2>{client.companyName}</h2><p>{client.ownerName} · <span dir="ltr">{client.ownerEmail}</span></p></div><div className="admin-client-profile-links"><Link href={`/linkly-command-7f3a9/logs?client=${client.tenantId}`}>السجل الكامل</Link><Link href={`/linkly-command-7f3a9/payments?client=${client.tenantId}`}>كل المدفوعات</Link></div></section>
    <section className="admin-client-profile-grid"><article className="admin-card"><h3>الاشتراك</h3><dl><div><dt>الباقة</dt><dd>{client.plan}</dd></div><div><dt>الدورة</dt><dd>{client.billingCycle}</dd></div><div><dt>التجديد</dt><dd>{client.renewalAt || "غير محدد"}</dd></div><div><dt>حالة المتابعة</dt><dd className={renewal?.tier === "overdue" ? "profile-danger" : ""}>{renewal?.label || "طبيعي"}</dd></div></dl></article><article className="admin-card"><h3>الفوترة</h3><dl><div><dt>الفاتورة الشهرية</dt><dd>{formatNumber(invoice)} ر.س</dd></div><div><dt>المحصل</dt><dd>{formatNumber(paid)} ر.س</dd></div><div><dt>المستحق</dt><dd>{formatNumber(pending)} ر.س</dd></div><div><dt>العمليات</dt><dd>{formatNumber(clientPayments.length)}</dd></div></dl></article><article className="admin-card"><h3>الاستخدام والحدود</h3><dl><div><dt>المحادثات</dt><dd>{formatNumber(client.conversationCount)}</dd></div><div><dt>المستخدمون</dt><dd>{formatNumber(client.employeeCount)} / {formatNumber(client.employeeLimit)}</dd></div><div><dt>تجاوز الحد</dt><dd className={extraUsers ? "profile-danger" : ""}>{extraUsers ? `${formatNumber(extraUsers)} مستخدم` : "لا يوجد"}</dd></div><div><dt>رصيد الحملات</dt><dd>{formatNumber(client.campaignBalance)}</dd></div></dl></article></section>
    <section className="admin-client-profile-columns"><article className="admin-card"><div className="admin-card-head"><div><h2>أحدث المدفوعات</h2><p>آخر خمس عمليات مرتبطة بهذا العميل.</p></div></div><div className="admin-profile-feed">{clientPayments.slice(0,5).map((item) => <div key={item.id}><span className={`admin-pill ${statusClass(item.status)}`}>{item.status}</span><div><strong>{formatNumber(item.amount)} ر.س · {item.source}</strong><small>{item.completedAt || item.createdAt} · <span dir="ltr">{item.moyasarId || "—"}</span></small></div></div>)}{!clientPayments.length && <p className="admin-empty-state">لا توجد مدفوعات مرتبطة.</p>}</div></article><article className="admin-card"><div className="admin-card-head"><div><h2>أحدث النشاطات</h2><p>آخر خمس أحداث في سجل التدقيق.</p></div></div><div className="admin-profile-feed">{clientLogs.slice(0,5).map((item) => <div key={item.id}><span className={`admin-pill ${statusClass(item.level)}`}>{item.level}</span><div><strong>{item.message}</strong><small>{item.at} · {item.source}</small></div></div>)}{!clientLogs.length && <p className="admin-empty-state">لا توجد أحداث مرتبطة.</p>}</div></article></section></>;
}
