// The editable texts of the home pages (from app/page.tsx and app/en/page.tsx), in page order.
// Each default must appear in its page file (a test keeps them in sync); admin overrides are
// stored by the default text's id (see lib/landing-content.ts).
export type LandingSlot = { label: string; text: string; multiline: boolean };

export const LANDING_SLOTS: Record<"ar" | "en", LandingSlot[]> = {
  ar: [
    { label: "الواجهة العلوية: الشارة الصغيرة", text: "منصة واحدة لكل فريقك", multiline: false },
    { label: "الواجهة العلوية: العنوان الرئيسي (H1) - الجزء الأول", text: "رد أسرع على عملائك ", multiline: false },
    { label: "الواجهة العلوية: العنوان الرئيسي (H1) - الجزء المميز", text: "ولا تضيع ولا محادثة", multiline: false },
    { label: "الواجهة العلوية: الوصف", text: "واتساب وإنستغرام وفيسبوك وتيليجرام والبريد وغيرها من منصات التواصل — فريقك يرد ويوزّع ويتابع من صندوق وارد واحد.", multiline: true },
    { label: "الواجهة العلوية: زر البدء", text: "ابدأ تجربتك مجانًا", multiline: false },
    { label: "قسم المشكلة - الشارة", text: "المشكلة", multiline: false },
    { label: "قسم المشكلة - العنوان (H2)", text: "قنوات متعددة. عشرات المحادثات. فريق واحد يحاول يلحق عليها.", multiline: true },
    { label: "قسم المشكلة - الوصف", text: "التنقل بين التطبيقات والجوالات يبطئ الرد ويخفي المسؤول ويجعل متابعة العميل تعتمد على الذاكرة.", multiline: true },
    { label: "قسم المنتج - الشارة", text: "المنتج", multiline: false },
    { label: "قسم المنتج - العنوان (H2)", text: "واجهة واحدة ترى فيها ما يحتاجه الفريق الآن", multiline: true },
    { label: "قسم المنتج - الوصف", text: "من أول رسالة إلى الإغلاق، تبقى المحادثة والعميل والمسؤول والخطوة التالية في نفس السياق.", multiline: true },
    { label: "قسم القنوات - الشارة", text: "القنوات", multiline: false },
    { label: "قسم القنوات - العنوان (H2)", text: "كل قناة بطبيعتها. إدارة واحدة لفريقك.", multiline: true },
    { label: "قسم القنوات - الوصف", text: "فعّل القنوات التي يحتاجها نشاطك، واجعل الفريق يعمل من صندوق وارد واحد.", multiline: true },
    { label: "قسم المزايا - الشارة", text: "المميزات", multiline: false },
    { label: "قسم المزايا - العنوان (H2)", text: "كل ما يحتاجه فريقك لإدارة المحادثة بوضوح", multiline: true },
    { label: "قسم المزايا - الوصف", text: "أدوات عملية مبنية حول سير العمل اليومي، لا قائمة طويلة من المزايا النظرية.", multiline: true },
    { label: "قسم طريقة العمل - الشارة", text: "طريقة العمل", multiline: false },
    { label: "قسم طريقة العمل - العنوان (H2)", text: "ابدأ خلال أربع خطوات", multiline: true },
    { label: "قسم طريقة العمل - الوصف", text: "مسار واضح من إنشاء الحساب إلى أول محادثة يديرها فريقك.", multiline: true },
    { label: "قسم حالات الاستخدام - الشارة", text: "حالات الاستخدام", multiline: false },
    { label: "قسم حالات الاستخدام - العنوان (H2)", text: "من أول استفسار إلى عميل تمت خدمته", multiline: true },
    { label: "قسم الأمان - الشارة", text: "الأمان والثقة", multiline: false },
    { label: "قسم الأمان - العنوان (H2)", text: "بيانات عملائك تستحق حماية على مستوى أعمالك", multiline: true },
    { label: "قسم الأمان - الوصف", text: "الحماية جزء أساسي من المنتج، من تسجيل الدخول إلى ربط قنواتك.", multiline: true },
    { label: "قسم الأسعار - الشارة", text: "الأسعار", multiline: false },
    { label: "قسم الأسعار - العنوان (H2)", text: "باقة واضحة لكل مرحلة من نمو فريقك", multiline: true },
    { label: "قسم الأسعار - الوصف", text: "ابدأ بالتجربة أولًا، ثم اختر السعة والأدوات المناسبة لطريقة عملك.", multiline: true },
    { label: "قسم الأسئلة الشائعة - الشارة", text: "الأسئلة الشائعة", multiline: false },
    { label: "قسم الأسئلة الشائعة - العنوان (H2)", text: "إجابات واضحة قبل أن تبدأ", multiline: true },
    { label: "الدعوة الختامية: الشارة", text: "ابدأ اليوم", multiline: false },
    { label: "الدعوة الختامية: العنوان", text: "خل فريقك يركز على العميل، مو على التنقل بين التطبيقات.", multiline: true },
    { label: "الدعوة الختامية: الوصف", text: "ابدأ تجربة Linkly مجانًا لمدة 3 أيام.", multiline: true },
    { label: "الدعوة الختامية: ملاحظة تحت الزر", text: "بدون بطاقة دفع", multiline: false },
  ],
  en: [
    { label: "Hero: eyebrow", text: "One workspace for your whole team", multiline: false },
    { label: "Hero: headline (H1) - first part", text: "Reply faster to customers ", multiline: false },
    { label: "Hero: headline (H1) - highlighted part", text: "and never lose a conversation", multiline: false },
    { label: "Hero: description", text: "WhatsApp, Instagram, Facebook, Telegram, email and more of your messaging platforms — your team replies, routes and follows up from one inbox.", multiline: true },
    { label: "Hero: start button", text: "Start your free trial", multiline: false },
    { label: "Section: Problem - kicker", text: "THE PROBLEM", multiline: false },
    { label: "Section: Problem - heading (H2)", text: "Multiple channels. Dozens of conversations. One team trying to keep up.", multiline: true },
    { label: "Section: Problem - description", text: "Switching between apps and phones slows down replies, hides who owns what, and makes follow-up depend on memory.", multiline: true },
    { label: "Section: Product - kicker", text: "THE PRODUCT", multiline: false },
    { label: "Section: Product - heading (H2)", text: "One interface showing exactly what your team needs right now", multiline: true },
    { label: "Section: Product - description", text: "From the first message to close, the conversation, customer, owner and next step all stay in the same context.", multiline: true },
    { label: "Section: Channels - kicker", text: "CHANNELS", multiline: false },
    { label: "Section: Channels - heading (H2)", text: "Every channel on its own terms. One place to manage them.", multiline: true },
    { label: "Section: Channels - description", text: "Turn on the channels your business needs, and let the team work from a single inbox.", multiline: true },
    { label: "Section: Features - kicker", text: "FEATURES", multiline: false },
    { label: "Section: Features - heading (H2)", text: "Everything your team needs to manage conversations clearly", multiline: true },
    { label: "Section: Features - description", text: "Practical tools built around the daily workflow, not a long list of theoretical features.", multiline: true },
    { label: "Section: How it works - kicker", text: "HOW IT WORKS", multiline: false },
    { label: "Section: How it works - heading (H2)", text: "Get started in four steps", multiline: true },
    { label: "Section: How it works - description", text: "A clear path from creating your account to your team's first managed conversation.", multiline: true },
    { label: "Section: Use cases - kicker", text: "USE CASES", multiline: false },
    { label: "Section: Use cases - heading (H2)", text: "From the first inquiry to a served customer", multiline: true },
    { label: "Section: Security - kicker", text: "SECURITY & TRUST", multiline: false },
    { label: "Section: Security - heading (H2)", text: "Your customers' data deserves business-grade protection", multiline: true },
    { label: "Section: Security - description", text: "Protection is a core part of the product, from signing in to connecting your channels.", multiline: true },
    { label: "Section: Pricing - kicker", text: "PRICING", multiline: false },
    { label: "Section: Pricing - heading (H2)", text: "A clear plan for every stage of your team's growth", multiline: true },
    { label: "Section: Pricing - description", text: "Start with the free trial first, then choose the capacity and tools that fit how you work.", multiline: true },
    { label: "Section: FAQ - kicker", text: "FAQ", multiline: false },
    { label: "Section: FAQ - heading (H2)", text: "Clear answers before you start", multiline: true },
    { label: "Final call to action: badge", text: "START TODAY", multiline: false },
    { label: "Final call to action: headline", text: "Let your team focus on the customer, not on switching between apps.", multiline: true },
    { label: "Final call to action: description", text: "Try Linkly free for 3 days.", multiline: true },
    { label: "Final call to action: note under button", text: "No card required", multiline: false },
  ]
};
